import { StyleSheet } from "@react-pdf/renderer";
import { COLORES as C, PAGINA, TIPOGRAFIA as T } from "./tema";

const { tamanos: S } = T;

export const estilos = StyleSheet.create({
  pagina: {
    backgroundColor: C.marfil,
    color: C.marino,
    fontFamily: T.texto,
    fontSize: S.cuerpo,
    lineHeight: 1.45,
    paddingTop: PAGINA.margenSuperior,
    paddingBottom: PAGINA.margenInferior,
    paddingHorizontal: PAGINA.margen,
  },

  // Portada
  portada: { backgroundColor: C.marfil, padding: 22, fontFamily: T.texto, color: C.marino },
  marcoExterior: { flex: 1, borderWidth: 1.2, borderColor: C.dorado, padding: 4 },
  marcoInterior: { flex: 1, borderWidth: 0.5, borderColor: C.dorado, alignItems: "center", paddingTop: 46 },
  portadaLogo: { width: 270 },
  ornamento: { flexDirection: "row", alignItems: "center", marginVertical: 22 },
  ornamentoLinea: { width: 70, height: 0.7, backgroundColor: C.dorado },
  ornamentoRombo: { width: 6, height: 6, backgroundColor: C.dorado, transform: "rotate(45deg)", marginHorizontal: 8 },
  portadaTipo: { fontSize: S.pequeno, letterSpacing: 3, color: C.doradoTexto, fontWeight: 600, textTransform: "uppercase" },
  portadaNombre: { fontFamily: T.titulos, fontSize: S.portada, fontWeight: 600, marginTop: 14, textAlign: "center", lineHeight: 1.15, paddingHorizontal: 40 },
  portadaLema: { fontFamily: T.titulos, fontStyle: "italic", fontSize: 15, color: C.marinoSuave, marginTop: 6, textAlign: "center" },
  portadaDescripcion: { fontSize: 10.5, color: C.pizarra, textAlign: "center", lineHeight: 1.6, marginTop: 18, width: 380 },
  portadaMeta: { flexDirection: "row", marginTop: 26, gap: 24 },
  metaBloque: { alignItems: "center", maxWidth: 250 },
  indice: { marginTop: 28, alignItems: "center" },
  indiceLista: { marginTop: 6, width: 170 },
  indiceItem: { flexDirection: "row", marginBottom: 2 },
  indiceNum: { width: 20, fontFamily: T.titulos, fontSize: 12.5, color: C.doradoTexto, fontWeight: 700 },
  indiceTexto: { fontFamily: T.titulos, fontSize: 12.5, color: C.marinoSuave },
  metaEtiqueta: { fontSize: S.micro, letterSpacing: 1.5, textTransform: "uppercase", color: C.doradoTexto, fontWeight: 600 },
  metaValor: { fontSize: 9.5, marginTop: 2 },
  panelPensamiento: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: C.marino,
    paddingVertical: 30,
    paddingHorizontal: 56,
    alignItems: "center",
  },
  pensamientoEmblema: { width: 34, height: 34, marginBottom: 12 },
  pensamientoTexto: { fontFamily: T.titulos, fontStyle: "italic", fontSize: S.pensamiento, color: C.doradoClaro, textAlign: "center", lineHeight: 1.4 },
  pensamientoAutor: { fontSize: S.pequeno, color: C.marfil, marginTop: 10, letterSpacing: 1, textAlign: "center" },
  pensamientoRef: { fontSize: S.micro, color: C.linea, marginTop: 3, textAlign: "center" },
  cintaDemo: {
    position: "absolute",
    top: 18,
    right: 18,
    backgroundColor: C.aviso,
    color: C.blanco,
    fontSize: S.micro,
    fontWeight: 700,
    letterSpacing: 2,
    paddingVertical: 4,
    paddingHorizontal: 10,
  },

  // Encabezado, pie y marca de agua
  encabezado: {
    position: "absolute",
    top: 26,
    left: PAGINA.margen,
    right: PAGINA.margen,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    paddingBottom: 8,
    borderBottomWidth: 0.6,
    borderBottomColor: C.dorado,
  },
  encabezadoLogo: { height: 24 },
  encabezadoTexto: { fontSize: S.micro + 0.5, color: C.pizarra, textAlign: "right" },
  pie: {
    position: "absolute",
    top: PAGINA.alto - 46,
    left: PAGINA.margen,
    right: PAGINA.margen,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 7,
    borderTopWidth: 0.6,
    borderTopColor: C.dorado,
    fontSize: S.micro,
    color: C.pizarra,
  },
  pieEmblema: { width: 12, height: 12 },
  marcaAgua: { position: "absolute", top: 340, left: 0, right: 0, height: 110, justifyContent: "center", alignItems: "center", transform: "rotate(-35deg)" },
  marcaAguaTexto: { fontFamily: T.titulos, fontSize: 64, fontWeight: 700, color: C.aviso, opacity: 0.07, letterSpacing: 4 },

  // Secciones
  seccion: { marginBottom: 18 },
  seccionCabecera: { flexDirection: "row", alignItems: "center", marginBottom: 10 },
  seccionNumero: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 0.8,
    borderColor: C.dorado,
    color: C.doradoTexto,
    fontFamily: T.titulos,
    fontSize: 12,
    fontWeight: 700,
    textAlign: "center",
    paddingTop: 3,
    marginRight: 9,
  },
  seccionTitulo: { fontFamily: T.titulos, fontSize: S.h1, fontWeight: 600 },
  seccionIntro: { color: C.pizarra, marginBottom: 8 },
  h2: { fontFamily: T.titulos, fontSize: S.h2, fontWeight: 600, marginBottom: 4 },
  pequeno: { fontSize: S.pequeno, color: C.pizarra },

  tabla: { borderTopWidth: 0.5, borderTopColor: C.linea },
  fila: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: C.linea, paddingVertical: 5 },
  celdaEtiqueta: { width: "34%", color: C.pizarra, fontSize: S.pequeno + 0.5, paddingRight: 8 },
  celdaValor: { width: "66%" },

  tarjeta: { backgroundColor: C.blanco, borderWidth: 0.5, borderColor: C.linea, borderRadius: 4, padding: 12, marginBottom: 10 },
  tarjetaCabecera: { flexDirection: "row", alignItems: "center", marginBottom: 6 },
  numeroCirculo: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: C.marino,
    borderWidth: 1.5,
    borderColor: C.dorado,
    color: C.doradoClaro,
    fontFamily: T.titulos,
    fontSize: 20,
    fontWeight: 700,
    textAlign: "center",
    paddingTop: 7,
    marginRight: 12,
  },
  destacado: { fontSize: S.micro, color: C.doradoTexto, fontWeight: 700, letterSpacing: 1, textTransform: "uppercase" },
  paso: { flexDirection: "row", paddingVertical: 2 },
  pasoNum: { width: 16, color: C.doradoTexto, fontSize: S.pequeno, fontWeight: 600 },
  pasoDesc: { width: 140, color: C.pizarra, fontSize: S.pequeno },
  pasoOp: { flex: 1, fontSize: S.pequeno },

  etiqueta: { fontSize: S.micro, fontWeight: 700, letterSpacing: 1.2, paddingVertical: 2, paddingHorizontal: 6, borderRadius: 2, marginRight: 6 },
  etiquetaTradicional: { color: C.doradoTexto, backgroundColor: C.pergamino, borderWidth: 0.5, borderColor: C.dorado },
  etiquetaIa: { color: C.ia, backgroundColor: C.iaFondo, borderWidth: 0.5, borderColor: C.ia },
  bordeTradicional: { borderLeftWidth: 2.5, borderLeftColor: C.dorado },
  bordeIa: { borderLeftWidth: 2.5, borderLeftColor: C.ia },
  parrafo: { marginBottom: 5 },
  cita: { color: C.doradoTexto, fontSize: S.pequeno },
  pregunta: { fontFamily: T.titulos, fontStyle: "italic", fontSize: 12, color: C.marinoSuave, marginTop: 2 },

  cajaAviso: { backgroundColor: C.avisoFondo, borderRadius: 4, padding: 12 },
  vineta: { flexDirection: "row", marginBottom: 3 },
  vinetaPunto: { width: 12, color: C.dorado },
  vinetaTexto: { flex: 1 },

  barra: { flexDirection: "row", height: 10, borderRadius: 5, overflow: "hidden", backgroundColor: C.linea, marginTop: 6, marginBottom: 4 },
  barraAportadas: { backgroundColor: C.marino },
  barraComplementarias: { backgroundColor: C.dorado },
  leyenda: { flexDirection: "row", gap: 14, fontSize: S.pequeno, color: C.pizarra, alignItems: "center" },
  leyendaItem: { flexDirection: "row", alignItems: "center" },
  leyendaMuestra: { width: 8, height: 8, borderRadius: 2, marginRight: 4 },
  fuente: { flexDirection: "row", marginBottom: 4 },
  fuenteNum: { width: 22, color: C.doradoTexto, fontWeight: 600 },

  campoVacio: { color: C.aviso, fontStyle: "italic" },
  cierre: { textAlign: "center", marginTop: 12 },
});
